/*
 * XlibConf.h -- Xlib build configuration for the ReactOS POSIX subsystem.
 * (In modular X.Org this file is generated by configure.)
 *
 * Single-threaded: the NT4-style subsystem has no pthreads yet, so neither
 * XTHREADS nor XUSE_MTSAFE_API is defined.
 *
 * MIT/X license (see copyright.h).
 */
#ifndef _XLIBCONF_H_
#define _XLIBCONF_H_

/* #undef XTHREADS */
/* #undef XUSE_MTSAFE_API */

#endif /* _XLIBCONF_H_ */
